---
title: "Thematics"
output:
  html_document:
    df_print: paged
---

## Layers available on GPKG:

```{r}
rm(list = ls())

WorldLink="https://github.com/lcampos2111/Tarea-1/raw/refs/heads/main/World_8857.gpkg/"
library(sf)
st_layers(WorldLink)
```

## Reading some layers:

```{r, message=FALSE}
World <- st_read(WorldLink, layer = "continent")
WorldMob_ddm <- st_read(WorldLink, layer = "value_ddm")
WorldMob_psm <- st_read(WorldLink, layer = "value_psm")

```

## Checking CRS

```{r}
st_crs(World)$epsg
```

# THE BASE
```{r}
library(ggplot2)
library(scales)

ggplot() +
  #call map
  geom_sf(data = World) + 
  # adjust datum 
  coord_sf(datum = st_crs(World)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") #labels
```
# DDM - static

```{r}
ggplot() + theme_light() +
  #base
  geom_sf(data = World,fill="white",color="grey80") +
  # layer
  geom_sf(data=WorldMob_ddm,
          alpha=0.1,#transparancy
          shape=20,
          size=1,
          color="red")+
  coord_sf(datum = st_crs(World)) # at the end of maps
  
```
# DDM - interactive

```{r}
library(leaflet)
# needs geographic CRS
ddm_4326 <- st_transform(WorldMob_ddm, crs = 4326)

leaflet() %>%
  addTiles() %>%  # base map
  addCircleMarkers(data = ddm_4326,
                   color="red",
                   radius = 0.01,
                   opacity = 0.1)
```

Almost the same:

```{r}
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  # names in english
  addCircleMarkers(data = ddm_4326,
                   color="red",
                   radius = 0.01,
                   opacity = 0.1)
```


# PSM - static

```{r}
ggplot() + theme_light() +
  #base
  geom_sf(data = World,fill="white",color="grey80") +
  # layer
  geom_sf(data=WorldMob_psm,
          shape=20,
          color="red",aes(size=size))+
  coord_sf(datum = st_crs(World)) # at the end of maps
  
```
# PSM - interactive

```{r}
# CRS for leaflet
psm_4326 <- st_transform(WorldMob_psm, crs = 4326)


leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = psm_4326,
                   # fillColor = "red",
                   # stroke = T, #border
                   # color="red", #border color
                   # fillOpacity = 1,
                   label = ~Country,
                   radius = ~size/10)
```


# CHORO - static

```{r}
ggplot() + theme_light() +
  #base
  geom_sf(data=World,
          aes(fill=population_density_FJ5_cat))+
  coord_sf(datum = st_crs(World)) +
  scale_fill_brewer(direction = 1,palette = 'RdBu')
  

  
```

# CHORO - interactive

```{r}
choro_4326 <- st_transform(World, crs = 4326)
#needed
choro_4326$population_density_FJ5_cat=ordered(choro_4326$population_density_FJ5_cat)
# First, create a color palette for your categorical variable
pal <- colorFactor(palette = "RdBu",
                   domain = choro_4326$population_density_FJ5_cat,
                   ordered = T,
                   reverse = F)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
  addPolygons(
    data = choro_4326,
    fillColor = ~pal(population_density_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1
    ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$population_density_FJ5_cat,
    )
```

```{r}
# Calculate the center of Africa for the home button
africa_center <- st_bbox(choro_4326) %>% 
  as.vector() %>% 
  {c(mean(c(.[1], .[3])), mean(c(.[2], .[4])))}  # Calculate center coordinates


leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
addPolygons(
    data = choro_4326,
    fillColor = ~pal(population_density_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1,
    label = lapply(
      paste("<strong>", choro_4326$Country, "</strong><br>",
            "Density: ", choro_4326$population_density),
      htmltools::HTML
    )
  ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$population_density_FJ5_cat,
    opacity = 0.7,
    title = "Population Density",
    position = "bottomright"
  )%>%
  addEasyButton(
    easyButton(
      icon = "fa-home", 
      title = "Reset to Africa View",
      onClick = JS(sprintf("function(btn, map){ map.setView([%f, %f], 3); }", 
                          World_center[2], World_center[1]))
    )
  )
```


